// <auto-generated />
using System;
using ETV.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETV.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260106082703_support personal vault items")]
    partial class supportpersonalvaultitems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ETV.src.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Team", b =>
                {
                    b.Property<byte[]>("TeamId")
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamName");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TeamMember", b =>
                {
                    b.Property<byte[]>("TeamId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("UserId")
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("EncryptedTeamKey")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("JoinedAt"));

                    b.Property<int>("KeyVersion")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("INT");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "KeyVersion");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("TeamUser", b =>
                {
                    b.Property<byte[]>("MembersId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("TeamsTeamId")
                        .HasColumnType("BINARY(16)");

                    b.HasKey("MembersId", "TeamsTeamId");

                    b.HasIndex("TeamsTeamId");

                    b.ToTable("TeamUser");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("KDFSalt")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VaultItem", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("EncryptedBlob")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("EncryptedItemKey")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("int");

                    b.Property<byte[]>("TeamId")
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.Property<byte[]>("UserId")
                        .HasColumnType("BINARY(16)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("VaultItems", t =>
                        {
                            t.HasCheckConstraint("CK_VaultItem_TeamOrUser", "(TeamId IS NOT NULL AND UserId IS NULL) OR (TeamId IS NULL AND UserId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ETV.src.Entities.RefreshToken", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamMember", b =>
                {
                    b.HasOne("Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamUser", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VaultItem", b =>
                {
                    b.HasOne("Team", "Team")
                        .WithMany("VaultItems")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("User", "User")
                        .WithMany("VaultItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team", b =>
                {
                    b.Navigation("TeamMembers");

                    b.Navigation("VaultItems");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("TeamMembers");

                    b.Navigation("VaultItems");
                });
#pragma warning restore 612, 618
        }
    }
}
