FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install --global dotnet-ef --version 8.0.2
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /src

COPY . .
RUN dotnet restore
CMD ["dotnet", "ef", "database", "update"]
